variables:
  PSPath: "$(System.DefaultWorkingDirectory)/Test.ps1"
stages: 
  - build
  - deploy

unity-build-windows: 
  script: "echo 'Building for Windows...' 
  | ${PSPath} ${UNITY_PASS} ${UNITY_USER} ${UNITY_LICENCE}"
  stage: build
  tags: 
    - unity
unity-build-linux: 
  script: "echo 'Building for Linux...'"
  stage: build
  tags: 
    - unity

unity-build-android: 
  script: "echo 'Building for Android...'"
  stage: build
  tags: 
    - unity
